"""Flood alerts — auto-generated by analyses/pipeline runs, or issued manually."""

from datetime import datetime, timezone

from fastapi import APIRouter, Depends, Query

from ..db import require_db, serialize
from ..errors import bad_request
from ..schemas import AlertCreateRequest
from ..security import get_current_user
from ..services import geodata

router = APIRouter(prefix="/alerts", tags=["Alerts"])


@router.get("")
def list_alerts(
    district: str | None = Query(None, description="Filter by district name."),
    severity: str | None = Query(None, description="LOW | MODERATE | HIGH"),
    limit: int = Query(50, ge=1, le=200),
):
    """Newest alerts first, optionally filtered by district and/or severity."""
    db = require_db()
    query: dict = {}
    if district:
        actual_name, _, _ = geodata.find_district(district)
        query["district"] = actual_name
    if severity:
        sev = severity.upper().strip()
        if sev not in ("LOW", "MODERATE", "HIGH"):
            raise bad_request(
                "INVALID_SEVERITY", "severity must be LOW, MODERATE, or HIGH."
            )
        query["severity"] = sev

    docs = db.alerts.find(query).sort("created_at", -1).limit(limit)
    alerts = [serialize(d) for d in docs]
    return {"success": True, "count": len(alerts), "alerts": alerts}


@router.get("/mine")
def my_alerts(limit: int = Query(50, ge=1, le=200), user: dict = Depends(get_current_user)):
    """Alerts for the authenticated user's home district (mobile home screen)."""
    if not user.get("district"):
        raise bad_request(
            "NO_DISTRICT_SET",
            "Set a home district first via PUT /api/auth/me/district.",
        )
    db = require_db()
    docs = (
        db.alerts.find({"district": user["district"]})
        .sort("created_at", -1)
        .limit(limit)
    )
    alerts = [serialize(d) for d in docs]
    return {
        "success": True,
        "district": user["district"],
        "count": len(alerts),
        "alerts": alerts,
    }


@router.post("", status_code=201)
def create_alert(body: AlertCreateRequest, user: dict = Depends(get_current_user)):
    """Manually issue an alert (authenticated users only, e.g. an authority)."""
    actual_name, _, _ = geodata.find_district(body.district)
    db = require_db()
    doc = {
        "district": actual_name,
        "severity": body.severity,
        "message": body.message,
        "source": "manual",
        "issued_by": user["username"],
        "created_at": datetime.now(timezone.utc),
    }
    db.alerts.insert_one(doc)
    return {"success": True, "alert": serialize(doc)}
